apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: bootiful-service-pairname
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: bootiful-service-pairname
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/language: java
  source:
    image: harbor.services.tanzu.rocks/workshop/pairname-bootiful-service
